version: '3.8'
services:
 server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - ./shared:/app/shared
    command: npm i && npx ts-node server.ts

 client:
    build: ./korvax-test-client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
    command: npm i && npm run dev

 admin:
    build: ./korvax-test-admin
    ports:
      - "8081:8081"
    volumes:
      - ./admin:/app
    command: npm i && npm run dev