version: "3"
services:
 server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - ./shared:/shared
    command: /bin/sh -c "npm i && npx ts-node server.ts"

 client:
    build: ./korvax-test-client
    ports:
      - "8080:8080"
    volumes:
      - ./korvax-test-client:/app
      - ./shared:/shared
    command: /bin/sh -c "npm i && npm start"

 admin:
    build: ./korvax-test-admin
    ports:
      - "8081:8081"
    volumes:
      - ./korvax-test-admin:/app
      - ./shared:/shared
    command: /bin/sh -c "npm i && npm start"